yolo_descriptions = {
    "yolov3u.pt": "Enhanced version of YOLOv3 with updated features and improved performance for diverse object detection tasks.",
    "yolov5nu.pt": "Nano version of YOLOv5 for balanced speed and accuracy in resource-constrained devices.",
    "yolov5su.pt": "Small variant of YOLOv5 offering enhanced accuracy with moderate speed trade-off.",
    "yolov5mu.pt": "Medium-sized YOLOv5 model providing a good balance between speed and precision.",
    "yolov5lu.pt": "Large variant of YOLOv5 suited for tasks that prioritize accuracy over speed.",
    "yolov5xu.pt": "Extra-large version of YOLOv5 designed for maximum accuracy in high-performance contexts.",
    "yolov5n6u.pt": "Nano version optimized for higher input resolution (6 series) with improved real-time performance.",
    "yolov5s6u.pt": "Small model enhanced for larger input resolutions, offering better accuracy with moderate speed.",
    "yolov5m6u.pt": "Medium version applied to higher-resolution inputs, balancing speed and accuracy.",
    "yolov5l6u.pt": "Large model trained for high resolution, provides improved detection capabilities with a speed compromise.",
    "yolov5x6u.pt": "Extra-large model optimized for high-resolution input, delivering maximum accuracy.",
    "yolov8n.pt": "Highly optimized nano version of YOLOv8 for real-time object detection tasks.",
    "yolov8s.pt": "Small variant of YOLOv8, trading some speed for improved accuracy while maintaining efficiency.",
    "yolov8m.pt": "Medium YOLOv8 model catering to general-purpose detection tasks with balanced speed and performance.",
    "yolov8l.pt": "Larger YOLOv8 variant focused on high precision for detection tasks across more complex datasets.",
    "yolov8x.pt": "Extra-large YOLOv8 model designed for scenarios that demand maximum accuracy and detail.",
    "yolov9t.pt": "Tiny variant of YOLOv9 with programmable gradient information, optimizing accuracy in smaller models.",
    "yolov9s.pt": "Small variant of YOLOv9 leveraging programmable gradient information for efficient detection.",
    "yolov9m.pt": "Medium YOLOv9 model utilizing programmable gradient information for superior results.",
    "yolov9c.pt": "Compact YOLOv9 variant incorporating programmable gradient information for balanced tasks.",
    "yolov9e.pt": "Experimental YOLOv9 with programmable gradient features for cutting-edge detection capabilities.",
    "yolov10n.pt": "Nano-sized YOLOv10 model featuring NMS-free (non-maximum-suppression-free) training for faster inference.",
    "yolov10s.pt": "Small YOLOv10 variant with NMS-free training for real-time applications.",
    "yolov10m.pt": "Medium YOLOv10 model focused on higher accuracy and efficiency with NMS-free training methodology.",
    "yolov10l.pt": "Large variant of YOLOv10 offering high accuracy with NMS-free training for advanced detection.",
    "yolov10x.pt": "Extra-large YOLOv10 model designed for maximum accuracy, featuring NMS-free training at higher computational cost.",
    "yolo11n.pt": "Nano variant delivering state-of-the-art (SOTA) performance optimized for speed and resource constraints.",
    "yolo11s.pt": "Small model achieving SOTA object detection performance without sacrificing speed.",
    "yolo11m.pt": "Medium model offering SOTA performance for balanced accuracy and inference speed.",
    "yolo11l.pt": "Large model delivering SOTA performance with a focus on accuracy, suitable for intricate tasks.",
    "yolo11x.pt": "Extra-large variant pushing SOTA performance boundaries for the most demanding object detection tasks.",
}
