pin_descriptions = {
    "P0": "Camera pan servo PIN",
    "P1": "Camera tilt servo PIN",
    "P2": "Direction servo PIN",
    "D4": "Left motor direction PIN",
    "D5": "Right motor direction PIN",
    "P12": "Left motor speed PIN",
    "P13": "Right motor speed PIN",
    "A0": "Grayscale PIN",
    "A1": "Grayscale PIN",
    "A2": "Grayscale PIN",
    "D2": "Ultrasonic Trigger PIN",
    "D3": "Ultrasonic Echo PIN",
    "MCURST": "MCU Reset PIN",
}
