export const toggleableSettings = {
  fullscreen: {
    description: "Toggle fullscreen",
    label: "Fullscreen",
  },
  text_info_view: {
    description: "Toggles text information on or off",
    label: "Show gauges view",
  },
  speedometer_view: {
    label: "Show speedometer",
    description: "Toggle the speedometer display on or off",
  },
  car_model_view: {
    description: "Toggles the 3D view of the car on or off",
    label: "Show 3D view of the car",
  },
  virtual_mode: {
    description: "Toggle replacing camera view with a 3D model",
    label: "Hide camera and focus on 3D model",
  },
  auto_download_photo: {
    description: "Toggle auto-download of captured photos",
    label: "Auto-download of captured photos",
  },
  auto_measure_distance_mode: {
    description: "Toggle auto-measure distance mode",
    label: "Auto-measure distance mode",
  },
  autoplay_music: {
    description: "Toggle auto playing music",
    label: "Autoplay music",
  },
};

export const ttsLanguages = [
  "af",
  "ar",
  "bn",
  "bs",
  "ca",
  "cs",
  "cy",
  "da",
  "de",
  "el",
  "en",
  "en-au",
  "en-ca",
  "en-gb",
  "en-gh",
  "en-ie",
  "en-in",
  "en-ng",
  "en-nz",
  "en-ph",
  "en-tz",
  "en-uk",
  "en-us",
  "en-za",
  "eo",
  "es",
  "es-es",
  "es-us",
  "et",
  "fi",
  "fr",
  "fr-ca",
  "fr-fr",
  "hi",
  "hr",
  "hu",
  "hy",
  "id",
  "is",
  "it",
  "ja",
  "jw",
  "km",
  "ko",
  "la",
  "lv",
  "mk",
  "ml",
  "mr",
  "my",
  "ne",
  "nl",
  "no",
  "pl",
  "pt",
  "pt-br",
  "pt-pt",
  "ro",
  "ru",
  "si",
  "sk",
  "sq",
  "sr",
  "su",
  "sv",
  "sw",
  "ta",
  "te",
  "th",
  "tl",
  "tr",
  "uk",
  "vi",
  "zh-cn",
  "zh-tw",
];
